import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :munchkin, MunchkinWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :debug

config :munchkin, Munchkin.Repo,
  database: "munchkin_prod",
  stacktrace: false

config :munchkin, Munchkin.Engine.Jkse,
  database_id: "95cc770e-1864-430c-bdcd-bbc71c20c804",
  instance: {Munchkin.Inventory, :get_source}

config :munchkin, Munchkin.Engine.Factset,
  database_id: "738eb45b-ae86-47f4-9916-b4d775e4a5b9",
  instance: {Munchkin.Inventory, :get_source}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
