@BASE_URL = http://localhost:4000/api/v1
@user_email = another.email@gmail.com
@user_password = satrio1234S

# // @user_password = KudaMakanKalengKacang


### List products

GET {{BASE_URL}}/products HTTP/1.1
Content-Type: application/json


### Register a user

POST {{BASE_URL}}/registrations HTTP/1.1
Content-Type: application/json

{
  "email": "{{user_email}}",
  "firstname": "Satrio",
  "lastname": "Nugroho",
  "password": "{{user_password}}"
}


### CREATE_SESSION

POST {{BASE_URL}}/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "{{user_password}}",
  "source": "excel"
}


### SESSION_FROM_REFRESH

POST {{BASE_URL}}/sessions HTTP/1.1
Content-Type: application/json

{
  "refresh_token": "{{CREATE_SESSION.response.body.$.data.tokens.refresh}}"
}


### FORGOT_PASSWORD

GET {{BASE_URL}}/forgot_password?email={{user_email}} HTTP/1.1
Content-Type: application/json


### GET current users

GET {{BASE_URL}}/accounts HTTP/1.1
Authorization: Bearer {{CREATE_SESSION.response.body.$.data.tokens.access}}
Content-Type: application/json


### Two factor request

POST {{BASE_URL}}/accounts?action=two_factor HTTP/1.1
Authorization: Bearer {{CREATE_SESSION.response.body.$.data.tokens.access}}
Content-Type: application/json


### Two factor validate

POST {{BASE_URL}}/accounts HTTP/1.1
Authorization: Bearer {{CREATE_SESSION.response.body.$.data.tokens.access}}
Content-Type: application/json

{
  "action": "validate_two_factor",
  "code": "641874"
}


### Delete two factor

POST {{BASE_URL}}/accounts HTTP/1.1
Authorization: Bearer {{CREATE_SESSION.response.body.$.data.tokens.access}}
Content-Type: application/json

{
  "action": "delete_two_factor",
  "id": "11"
}
